# Generated by Django 6.0.5 on 2026-07-20 12:24

from django.db import migrations, models

from django.utils.text import slugify


def generar_slugs_existentes(apps, schema_editor):
    Categoria = apps.get_model("core", "Categoria")
    for cat in Categoria.objects.all():
        if not cat.slug or cat.slug.strip() == "":
            cat.slug = slugify(cat.nombre)
            cat.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_categoria_remove_productoimagen_imagen_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(generar_slugs_existentes),
    ]
