# Generated by Django 6.0.5 on 2026-07-20 16:45

from django.db import migrations
from django.utils.text import slugify


def trasladar_datos_de_modelos(apps, schema_editor):
    # Usamos apps.get_model para evitar importar los modelos directamente,
    # esto asegura que usemos la versión histórica correcta de la base de datos.
    Producto = apps.get_model("store", "Producto")
    Marca = apps.get_model("store", "Marca")
    ModeloDispositivo = apps.get_model("store", "ModeloDispositivo")

    for producto in Producto.objects.all():
        texto = producto.modelos_disponibles.strip()
        if texto:
            # Tomamos la primera palabra como la Marca (ej: "Apple")
            # y el resto del texto como el Modelo (ej: "iPhone 15 Pro")
            partes = texto.split(" ", 1)
            nombre_marca = partes[0]
            nombre_modelo = partes[1] if len(partes) > 1 else "Genérico"

            # 1. Creamos o traemos la Marca basándonos en el nombre único
            marca_obj, _ = Marca.objects.get_or_create(
                nombre=nombre_marca, defaults={"slug": slugify(nombre_marca)}
            )

            # 2. Creamos o traemos el Modelo asociado a esa específica Marca
            modelo_obj, _ = ModeloDispositivo.objects.get_or_create(
                marca=marca_obj,
                nombre=nombre_modelo,
                defaults={"slug": slugify(nombre_modelo)},
            )

            # 3. Guardamos el puntero (FK) en nuestro producto actual
            producto.modelo_dispositivo = modelo_obj
            producto.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_marca_modelodispositivo_producto_modelo_dispositivo_and_more"),
    ]

    operations = []
