# Generated by Django 6.0.5 on 2026-07-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_migrar_modelos_a_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='modelo_dispositivo',
        ),
        migrations.AddField(
            model_name='producto',
            name='modelos_dispositivo',
            field=models.ManyToManyField(blank=True, related_name='productos', to='core.modelodispositivo'),
        ),
    ]
