# Generated by Django 6.0.5 on 2026-07-20 17:40

from django.db import migrations
from django.utils.text import slugify


def trasladar_multiples_modelos(apps, schema_editor):
    Producto = apps.get_model("core", "Producto")
    Marca = apps.get_model("core", "Marca")
    ModeloDispositivo = apps.get_model("core", "ModeloDispositivo")

    for producto in Producto.objects.all():
        texto = producto.modelos_disponibles.strip()
        if texto:
            # Reemplazamos barras diagonales y pipes por comas para estandarizar
            texto_normalizado = texto.replace("/", ",").replace("|", ",")

            # Separamos por coma todos los modelos posibles
            items = [i.strip() for i in texto_normalizado.split(",") if i.strip()]

            for item in items:
                partes = item.split(" ", 1)
                nombre_marca = partes[0].strip()
                nombre_modelo = partes[1].strip() if len(partes) > 1 else "Genérico"

                if not nombre_marca:
                    continue

                # Calculamos slugs iniciales
                slug_marca = slugify(nombre_marca)[:50]
                slug_modelo = slugify(nombre_modelo)[:50]

                # Forzamos que los nombres visibles tampoco superen los 50 caracteres
                nombre_marca_limpio = nombre_marca[:50]
                nombre_modelo_limpio = nombre_modelo[:50]

                # 1. Crear o traer la Marca
                marca_obj, _ = Marca.objects.get_or_create(
                    slug=slug_marca, defaults={"nombre": nombre_marca_limpio}
                )

                # 2. Crear o traer el Modelo asegurando que no exceda los 50 caracteres
                modelo_obj, _ = ModeloDispositivo.objects.get_or_create(
                    slug=slug_modelo,
                    defaults={
                        "nombre": nombre_modelo_limpio,
                        "marca": marca_obj,
                    },
                )

                # 3. Asociamos el modelo al producto de forma segura
                producto.modelos_dispositivo.add(modelo_obj)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_producto_modelo_dispositivo_and_more"),
    ]

    operations = [
        migrations.RunPython(trasladar_multiples_modelos),
    ]
