# Generated by Django 6.0.5 on 2026-07-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_migrar_a_muchos_modelos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='modelos_disponibles',
        ),
    ]
